server:
  port: 8080

spring:
  application:
    name: api-gateway

gateway:
  cors:
    allowed-origins: "*"
  jwt:
    secret-key: "gateway-secret-key"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
