server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
        - id: contactmessage-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/contact/**
        - id: nutritionix-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/food/**
        - id: favorite-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/favorites/**


  cors:
    allowed-origins: "*"
    allowed-methods: "GET, POST, PUT, DELETE"
    allowed-headers: "*"